# Generated by Django 4.2.7 on 2023-11-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialChatPregunta',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('pregunta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_chat_preguntas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialChatRespuestas',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('historial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_ChatGPT.historialchatpregunta')),
            ],
            options={
                'db_table': 'chat_respuestas',
                'ordering': ['-created_at'],
            },
        ),
    ]
