# Generated by Django 4.2.7 on 2023-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_ChatGPT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialchatrespuestas',
            table='tbl_chat_respuestas',
        ),
    ]
